# Use the official Node image
FROM node:18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Run the app with nodemon
CMD ["nodemon", "server.js"]
